export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'